---
- name: Recolectar y enviar logs por correo
  hosts: all
  become: yes
  vars:
    smtp_host: "smtp.mailtrap.io"      # O smtp.gmail.com
    smtp_port: "2525"                  # O 587
    smtp_user: "tu_usuario"
    smtp_password: "tu_password_de_aplicacion"
    correo_origen: "ansible@tuempresa.com"
    correo_destino: "admin@tuempresa.com"
  
  roles:
    - email_logs
