---
- name: Recolectar y enviar logs por correo
  hosts: all
  become: yes
  vars:
    # --- Configuración del servidor de Gmail ---
    smtp_host: "smtp.gmail.com"
    smtp_port: "587"
    smtp_user: "proyectostrabajopruebas@gmail.com"
    smtp_password: "lyxm dbjs qgem blgj "  # <-- Aquí va la contraseña de 16 letras (TODO JUNTO, sin espacios)
    
    # --- Configuración de los correos ---
    correo_origen: "proyectostrabajopruebas@gmail.com"
    correo_destino: "eromero@sorint.com"  # Puedes poner el de tu empresa para recibirlo allí
  
  roles:
    - email_logs
